apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    uid: prometheus
    isDefault: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - datasourceUid: jaeger
          name: trace_id

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    uid: jaeger
    isDefault: false

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki
    isDefault: false
    jsonData:
      derivedFields:
        - datasourceUid: jaeger
          matcherType: label
          matcherRegex: "trace_id"
          name: Trace
          url: "$${__value.raw}"
