// <auto-generated />
using System;
using Kahoot.Domain.Enums;
using Kahoot.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kahoot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260929130705_AllowConcurrentJoinRecoveryTokens")]
    partial class AllowConcurrentJoinRecoveryTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "game_status", new[] { "created", "finished", "leaderboard", "lobby", "question_active", "question_results" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "host", "system_admin" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_status", new[] { "active", "suspended" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kahoot.Domain.Entities.AnswerSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid>("GameQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_question_id");

                    b.Property<Guid>("HostAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_account_id");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("integer")
                        .HasColumnName("points_awarded");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("response_time_ms");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id")
                        .HasName("pk_answer_submissions");

                    b.HasAlternateKey("Id", "HostAccountId", "GameQuestionId")
                        .HasName("ak_answer_submissions_id_host_account_id_game_question_id");

                    b.HasIndex("GameId", "HostAccountId")
                        .HasDatabaseName("ix_answer_submissions_game_id_host_account_id");

                    b.HasIndex("GameQuestionId", "SubmittedAt")
                        .HasDatabaseName("ix_answer_submissions_question_time");

                    b.HasIndex("GameId", "GameQuestionId", "ParticipantId")
                        .IsUnique()
                        .HasDatabaseName("ux_answer_submissions_once_per_question");

                    b.HasIndex("GameQuestionId", "HostAccountId", "GameId")
                        .HasDatabaseName("ix_answer_submissions_game_question_id_host_account_id_game_id");

                    b.HasIndex("Id", "HostAccountId", "GameQuestionId")
                        .IsUnique()
                        .HasDatabaseName("ux_answer_submissions_id_host_account_question");

                    b.HasIndex("ParticipantId", "HostAccountId", "GameId")
                        .HasDatabaseName("ix_answer_submissions_participant_id_host_account_id_game_id");

                    b.ToTable("answer_submissions", (string)null);
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.AnswerSubmissionChoice", b =>
                {
                    b.Property<Guid>("AnswerSubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("answer_submission_id");

                    b.Property<Guid>("GameChoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_choice_id");

                    b.Property<Guid>("GameQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_question_id");

                    b.Property<Guid>("HostAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_account_id");

                    b.HasKey("AnswerSubmissionId", "GameChoiceId")
                        .HasName("pk_answer_submission_choices");

                    b.HasIndex("GameQuestionId", "GameChoiceId")
                        .HasDatabaseName("ix_answer_submission_choices_question_choice");

                    b.HasIndex("AnswerSubmissionId", "HostAccountId", "GameQuestionId")
                        .HasDatabaseName("ix_answer_submission_choices_answer_submission_id_host_account");

                    b.HasIndex("GameChoiceId", "HostAccountId", "GameQuestionId")
                        .HasDatabaseName("ix_answer_submission_choices_game_choice_id_host_account_id_ga");

                    b.ToTable("answer_submission_choices", (string)null);
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.Choice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("HostAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_account_id");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_choices");

                    b.HasIndex("Id", "HostAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_choices_id_host_account");

                    b.HasIndex("QuestionId", "HostAccountId")
                        .HasDatabaseName("ix_choices_question_id_host_account_id");

                    b.HasIndex("QuestionId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_choices_question_order");

                    b.HasIndex("HostAccountId", "QuestionId", "OrderIndex")
                        .HasDatabaseName("ix_choices_host_account_question_order");

                    b.ToTable("choices", (string)null);
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CurrentQuestionIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_question_index");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<Guid>("HostAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_account_id");

                    b.Property<DateTimeOffset?>("HostGraceExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("host_grace_expires_at");

                    b.Property<bool>("IsTerminatedBySuspension")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_terminated_by_suspension");

                    b.Property<int>("NextSeatNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("next_seat_number");

                    b.Property<string>("Pin")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("pin");

                    b.Property<long>("PresenceVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("presence_version");

                    b.Property<int>("ReservedParticipantCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("reserved_participant_count");

                    b.Property<Guid>("SourceQuizId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_quiz_id");

                    b.Property<long>("StateVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("state_version");

                    b.Property<GameStatus>("Status")
                        .HasColumnType("game_status")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_games");

                    b.HasAlternateKey("Id", "HostAccountId")
                        .HasName("ak_games_id_host_account_id");

                    b.HasIndex("Pin")
                        .IsUnique()
                        .HasDatabaseName("ux_games_active_pin");

                    b.HasIndex("HostAccountId", "SourceQuizId")
                        .HasDatabaseName("ix_games_host_account_source_quiz");

                    b.HasIndex("HostAccountId", "Status")
                        .HasDatabaseName("ix_games_host_account_status");

                    b.HasIndex("Id", "HostAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_games_id_host_account");

                    b.HasIndex("SourceQuizId", "HostAccountId")
                        .HasDatabaseName("ix_games_source_quiz_id_host_account_id");

                    b.HasIndex("Status", "HostGraceExpiresAt")
                        .HasDatabaseName("ix_games_abandonment_sweep");

                    b.HasIndex("HostAccountId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_games_host_account_created_id");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.GameChoiceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GameQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_question_id");

                    b.Property<Guid>("HostAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_account_id");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<int>("SelectionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("selection_count");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_game_choice_snapshots");

                    b.HasAlternateKey("Id", "HostAccountId", "GameQuestionId")
                        .HasName("ak_game_choice_snapshots_id_host_account_id_game_question_id");

                    b.HasIndex("GameQuestionId", "HostAccountId")
                        .HasDatabaseName("ix_game_choice_snapshots_game_question_id_host_account_id");

                    b.HasIndex("GameQuestionId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_game_choices_question_order");

                    b.HasIndex("Id", "HostAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_game_choices_id_host_account");

                    b.HasIndex("Id", "HostAccountId", "GameQuestionId")
                        .IsUnique()
                        .HasDatabaseName("ux_game_choices_id_host_account_question");

                    b.ToTable("game_choice_snapshots", (string)null);
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.GameCommandIdempotency", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid>("CommandId")
                        .HasColumnType("uuid")
                        .HasColumnName("command_id");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("command_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HostAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_account_id");

                    b.Property<byte[]>("RequestHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponsePayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_payload");

                    b.Property<long>("ResultStateVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("result_state_version");

                    b.HasKey("GameId", "CommandId")
                        .HasName("pk_game_command_idempotency");

                    b.HasIndex("GameId", "HostAccountId")
                        .HasDatabaseName("ix_game_command_idempotency_game_id_host_account_id");

                    b.HasIndex("HostAccountId", "GameId", "CreatedAt")
                        .HasDatabaseName("ix_game_command_idempotency_host_account_game_time");

                    b.ToTable("game_command_idempotency", (string)null);
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.GameQuestionSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AcceptedAnswerCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("accepted_answer_count");

                    b.Property<int>("BasePoints")
                        .HasColumnType("integer")
                        .HasColumnName("base_points");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<int>("EffectiveEligibleParticipantCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("effective_eligible_participant_count");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid>("HostAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_account_id");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("image_url");

                    b.Property<int>("InitialEligibleParticipantCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("initial_eligible_participant_count");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<DateTimeOffset?>("ResultsMaterializedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("results_materialized_at");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_game_question_snapshots");

                    b.HasAlternateKey("Id", "HostAccountId")
                        .HasName("ak_game_question_snapshots_id_host_account_id");

                    b.HasAlternateKey("Id", "HostAccountId", "GameId")
                        .HasName("ak_game_question_snapshots_id_host_account_id_game_id");

                    b.HasIndex("GameId", "HostAccountId")
                        .HasDatabaseName("ix_game_question_snapshots_game_id_host_account_id");

                    b.HasIndex("GameId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_game_questions_game_order");

                    b.HasIndex("Id", "HostAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_game_questions_id_host_account");

                    b.HasIndex("ImageId", "HostAccountId")
                        .HasDatabaseName("ix_game_question_snapshots_image_id_host_account_id");

                    b.HasIndex("HostAccountId", "GameId", "OrderIndex")
                        .HasDatabaseName("ix_game_questions_host_account_game_order");

                    b.HasIndex("Id", "HostAccountId", "GameId")
                        .IsUnique()
                        .HasDatabaseName("ux_game_questions_id_host_account_game");

                    b.ToTable("game_question_snapshots", (string)null);
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ConnectionGeneration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("connection_generation");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayNickname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("display_nickname");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid>("HostAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_account_id");

                    b.Property<bool>("IsRemoved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_removed");

                    b.Property<byte[]>("JoinOperationIdHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("join_operation_id_hash");

                    b.Property<DateTimeOffset>("JoinRecoveryExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("join_recovery_expires_at");

                    b.Property<string>("NormalizedNickname")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("normalized_nickname");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("integer")
                        .HasColumnName("seat_number");

                    b.Property<long>("TotalScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("total_score");

                    b.HasKey("Id")
                        .HasName("pk_participants");

                    b.HasAlternateKey("Id", "HostAccountId", "GameId")
                        .HasName("ak_participants_id_host_account_id_game_id");

                    b.HasIndex("JoinOperationIdHash")
                        .IsUnique()
                        .HasDatabaseName("ux_participants_join_operation");

                    b.HasIndex("GameId", "HostAccountId")
                        .HasDatabaseName("ix_participants_game_id_host_account_id");

                    b.HasIndex("GameId", "JoinOperationIdHash")
                        .IsUnique()
                        .HasDatabaseName("ux_participants_game_join_operation");

                    b.HasIndex("GameId", "NormalizedNickname")
                        .IsUnique()
                        .HasDatabaseName("ux_participants_game_nickname");

                    b.HasIndex("GameId", "SeatNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_participants_game_seat");

                    b.HasIndex("HostAccountId", "GameId", "IsRemoved")
                        .HasDatabaseName("ix_participants_host_account_game_removed");

                    b.HasIndex("Id", "HostAccountId", "GameId")
                        .IsUnique()
                        .HasDatabaseName("ux_participants_id_host_account_game");

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.ParticipantSessionToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<Guid>("HostAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_account_id");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.HasKey("Id")
                        .HasName("pk_participant_session_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_participant_session_tokens_expires_at");

                    b.HasIndex("ParticipantId")
                        .HasDatabaseName("ix_participant_session_tokens_participant");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_participant_session_tokens_token_hash");

                    b.HasIndex("HostAccountId", "GameId", "ParticipantId")
                        .HasDatabaseName("ix_participant_tokens_host_account_game_participant");

                    b.HasIndex("ParticipantId", "HostAccountId", "GameId")
                        .HasDatabaseName("ix_participant_session_tokens_participant_id_host_account_id_g");

                    b.ToTable("participant_session_tokens", (string)null);
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BasePoints")
                        .HasColumnType("integer")
                        .HasColumnName("base_points");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<Guid>("HostAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_account_id");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid")
                        .HasColumnName("quiz_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasAlternateKey("Id", "HostAccountId")
                        .HasName("ak_questions_id_host_account_id");

                    b.HasIndex("Id", "HostAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_questions_id_host_account");

                    b.HasIndex("ImageId", "HostAccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_questions_image_id_host_account_id");

                    b.HasIndex("QuizId", "HostAccountId")
                        .HasDatabaseName("ix_questions_quiz_id_host_account_id");

                    b.HasIndex("QuizId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_questions_quiz_order");

                    b.HasIndex("HostAccountId", "QuizId", "OrderIndex")
                        .HasDatabaseName("ix_questions_host_account_quiz_order");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.QuestionImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HostAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_account_id");

                    b.Property<int>("PixelHeight")
                        .HasColumnType("integer")
                        .HasColumnName("pixel_height");

                    b.Property<int>("PixelWidth")
                        .HasColumnType("integer")
                        .HasColumnName("pixel_width");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("storage_path");

                    b.Property<DateTimeOffset?>("UnreferencedSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unreferenced_since");

                    b.HasKey("Id")
                        .HasName("pk_question_images");

                    b.HasAlternateKey("Id", "HostAccountId")
                        .HasName("ak_question_images_id_host_account_id");

                    b.HasIndex("StoragePath")
                        .IsUnique()
                        .HasDatabaseName("ux_question_images_storage_path");

                    b.HasIndex("UnreferencedSince")
                        .HasDatabaseName("ix_question_images_orphan_cleanup");

                    b.HasIndex("Id", "HostAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_question_images_id_host_account");

                    b.HasIndex("HostAccountId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_question_images_host_account_created_id");

                    b.ToTable("question_images", (string)null);
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<Guid>("HostAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_account_id");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<long>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_quizzes");

                    b.HasAlternateKey("Id", "HostAccountId")
                        .HasName("ak_quizzes_id_host_account_id");

                    b.HasIndex("Id", "HostAccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_quizzes_id_host_account");

                    b.HasIndex("HostAccountId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_quizzes_host_account_created_id");

                    b.ToTable("quizzes", (string)null);
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("FamilyCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("family_created_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTimeOffset?>("RotatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rotated_at");

                    b.Property<Guid>("TokenFamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("token_family_id");

                    b.Property<byte[]>("TokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_refresh_tokens_expires_at");

                    b.HasIndex("RevokedAt")
                        .HasDatabaseName("ix_refresh_tokens_revoked_at");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_refresh_tokens_token_hash");

                    b.HasIndex("UserId", "TokenFamilyId")
                        .HasDatabaseName("ix_refresh_tokens_user_family");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("DisplayUsername")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_username");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<long>("Revision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<UserRole>("Role")
                        .HasColumnType("user_role")
                        .HasColumnName("role");

                    b.Property<UserStatus>("Status")
                        .HasColumnType("user_status")
                        .HasColumnName("status");

                    b.Property<bool>("TerminationPending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("termination_pending");

                    b.Property<int>("TokenSecurityVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("token_security_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_username");

                    b.HasIndex("Role", "Status", "CreatedAt", "Id")
                        .HasDatabaseName("ix_users_admin_listing");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.AnswerSubmission", b =>
                {
                    b.HasOne("Kahoot.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId", "HostAccountId")
                        .HasPrincipalKey("Id", "HostAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_answer_submissions_games_game_id_host_account_id");

                    b.HasOne("Kahoot.Domain.Entities.GameQuestionSnapshot", null)
                        .WithMany()
                        .HasForeignKey("GameQuestionId", "HostAccountId", "GameId")
                        .HasPrincipalKey("Id", "HostAccountId", "GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_answer_submissions_game_question_snapshots_game_question_id");

                    b.HasOne("Kahoot.Domain.Entities.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId", "HostAccountId", "GameId")
                        .HasPrincipalKey("Id", "HostAccountId", "GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_answer_submissions_participants_participant_id_host_account");
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.AnswerSubmissionChoice", b =>
                {
                    b.HasOne("Kahoot.Domain.Entities.AnswerSubmission", null)
                        .WithMany()
                        .HasForeignKey("AnswerSubmissionId", "HostAccountId", "GameQuestionId")
                        .HasPrincipalKey("Id", "HostAccountId", "GameQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_answer_submission_choices_answer_submissions_answer_submiss");

                    b.HasOne("Kahoot.Domain.Entities.GameChoiceSnapshot", null)
                        .WithMany()
                        .HasForeignKey("GameChoiceId", "HostAccountId", "GameQuestionId")
                        .HasPrincipalKey("Id", "HostAccountId", "GameQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_answer_submission_choices_game_choice_snapshots_game_choice");
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.Choice", b =>
                {
                    b.HasOne("Kahoot.Domain.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId", "HostAccountId")
                        .HasPrincipalKey("Id", "HostAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_choices_questions_question_id_host_account_id");
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.Game", b =>
                {
                    b.HasOne("Kahoot.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("HostAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_games_users_host_account_id");

                    b.HasOne("Kahoot.Domain.Entities.Quiz", null)
                        .WithMany()
                        .HasForeignKey("SourceQuizId", "HostAccountId")
                        .HasPrincipalKey("Id", "HostAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_games_quizzes_source_quiz_id_host_account_id");
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.GameChoiceSnapshot", b =>
                {
                    b.HasOne("Kahoot.Domain.Entities.GameQuestionSnapshot", null)
                        .WithMany()
                        .HasForeignKey("GameQuestionId", "HostAccountId")
                        .HasPrincipalKey("Id", "HostAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_game_choice_snapshots_game_question_snapshots_game_question");
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.GameCommandIdempotency", b =>
                {
                    b.HasOne("Kahoot.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId", "HostAccountId")
                        .HasPrincipalKey("Id", "HostAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_game_command_idempotency_games_game_id_host_account_id");
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.GameQuestionSnapshot", b =>
                {
                    b.HasOne("Kahoot.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId", "HostAccountId")
                        .HasPrincipalKey("Id", "HostAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_game_question_snapshots_games_game_id_host_account_id");

                    b.HasOne("Kahoot.Domain.Entities.QuestionImage", null)
                        .WithMany()
                        .HasForeignKey("ImageId", "HostAccountId")
                        .HasPrincipalKey("Id", "HostAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_game_question_snapshots_question_images_image_id_host_accou");
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.Participant", b =>
                {
                    b.HasOne("Kahoot.Domain.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GameId", "HostAccountId")
                        .HasPrincipalKey("Id", "HostAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_participants_games_game_id_host_account_id");
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.ParticipantSessionToken", b =>
                {
                    b.HasOne("Kahoot.Domain.Entities.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId", "HostAccountId", "GameId")
                        .HasPrincipalKey("Id", "HostAccountId", "GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_participant_session_tokens_participants_participant_id_host");
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.Question", b =>
                {
                    b.HasOne("Kahoot.Domain.Entities.QuestionImage", "Image")
                        .WithOne()
                        .HasForeignKey("Kahoot.Domain.Entities.Question", "ImageId", "HostAccountId")
                        .HasPrincipalKey("Kahoot.Domain.Entities.QuestionImage", "Id", "HostAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_questions_question_images_image_id_host_account_id");

                    b.HasOne("Kahoot.Domain.Entities.Quiz", null)
                        .WithMany()
                        .HasForeignKey("QuizId", "HostAccountId")
                        .HasPrincipalKey("Id", "HostAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_quizzes_quiz_id_host_account_id");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.QuestionImage", b =>
                {
                    b.HasOne("Kahoot.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("HostAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_question_images_users_host_account_id");
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.Quiz", b =>
                {
                    b.HasOne("Kahoot.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("HostAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_quizzes_users_host_account_id");
                });

            modelBuilder.Entity("Kahoot.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Kahoot.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
