<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.15.0" />
    <PackageReference Include="Testcontainers.Redis" Version="4.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Kahoot.Application\Kahoot.Application.csproj" />
    <ProjectReference Include="..\..\src\Kahoot.Infrastructure\Kahoot.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\" />
  </ItemGroup>

</Project>
