namespace Kahoot.Application.Features.Games;

// State Transition Control Contract - Encapsulates client idempotency key and OCC version fence for all game control endpoints
public sealed record GameControlRequest(
    // Command Idempotency Key - UUIDv4 generated by client to deduplicate retried network commands
    Guid CommandId,
    // Optimistic Concurrency Control Fence - Monotonically increasing state version to reject out-of-order or duplicate state transitions
    long ExpectedStateVersion);
