extensions:
  jaeger_storage:
    backends:
      badger:
        badger:
          ephemeral: false
          directories:
            keys: /badger/keys
            values: /badger/data
          ttl:
            spans: 72h
  jaeger_query:
    storage:
      traces: badger
    http:
      endpoint: 0.0.0.0:16686

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  jaeger_storage_exporter:
    trace_storage: badger

service:
  extensions:
    - jaeger_storage
    - jaeger_query
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - jaeger_storage_exporter
